export const AppsCardData = [
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "pending",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "pending",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "approved",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
  {
    status: "rejected",
    name: "Olayiwola John D.",
    faculty: "Engineering",
    dept: "Chemical",
    date: "Feb 26, 2023",
  },
];
